apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carts
  namespace: sock-shop
spec:
  host: carts
  subsets:
  - labels:
      name: carts
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  host: carts-db
  subsets:
  - labels:
      name: carts-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: catalogue
  namespace: sock-shop
spec:
  host: catalogue
  subsets:
  - labels:
      name: catalogue
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: catalogue-db
  namespace: sock-shop
spec:
  host: catalogue-db
  subsets:
  - labels:
      name: catalogue-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: front-end
  namespace: sock-shop
spec:
  host: front-end
  subsets:
  - labels:
      name: front-end
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders
  namespace: sock-shop
spec:
  host: orders
  subsets:
  - labels:
      name: orders
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders-db
  namespace: sock-shop
spec:
  host: orders-db
  subsets:
  - labels:
      name: orders-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment
  namespace: sock-shop
spec:
  host: payment
  subsets:
  - labels:
      name: payment
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: queue-master
  namespace: sock-shop
spec:
  host: queue-master
  subsets:
  - labels:
      name: queue-master
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rabbitmq
  namespace: sock-shop
spec:
  host: rabbitmq
  subsets:
  - labels:
      name: rabbitmq
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: session-db
  namespace: sock-shop
spec:
  host: session-db
  subsets:
  - labels:
      name: session-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: shipping
  namespace: sock-shop
spec:
  host: shipping
  subsets:
  - labels:
      name: shipping
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user
  namespace: sock-shop
spec:
  host: user
  subsets:
  - labels:
      name: user
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-db
  namespace: sock-shop
spec:
  host: user-db
  subsets:
  - labels:
      name: user-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
