apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carts
  namespace: sock-shop
spec:
  host: carts
  subsets:
  - labels:
      name: carts
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 3
        http2MaxRequests: 31
        maxRequestsPerConnection: 43
        maxRetries: 71
      tcp:
        connectTimeout: 1ms
        maxConnections: 28
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: carts-db
  namespace: sock-shop
spec:
  host: carts-db
  subsets:
  - labels:
      name: carts-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 32
        http2MaxRequests: 85
        maxRequestsPerConnection: 56
        maxRetries: 39
      tcp:
        connectTimeout: 95ms
        maxConnections: 21
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: catalogue
  namespace: sock-shop
spec:
  host: catalogue
  subsets:
  - labels:
      name: catalogue
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 21
        http2MaxRequests: 15
        maxRequestsPerConnection: 59
        maxRetries: 79
      tcp:
        connectTimeout: 66ms
        maxConnections: 69
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: catalogue-db
  namespace: sock-shop
spec:
  host: catalogue-db
  subsets:
  - labels:
      name: catalogue-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 59
        http2MaxRequests: 201
        maxRequestsPerConnection: 51
        maxRetries: 71
      tcp:
        connectTimeout: 41ms
        maxConnections: 49
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: front-end
  namespace: sock-shop
spec:
  host: front-end
  subsets:
  - labels:
      name: front-end
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http: {}
      tcp: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders
  namespace: sock-shop
spec:
  host: orders
  subsets:
  - labels:
      name: orders
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 56
        http2MaxRequests: 36
        maxRequestsPerConnection: 82
        maxRetries: 47
      tcp:
        connectTimeout: 77ms
        maxConnections: 2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: orders-db
  namespace: sock-shop
spec:
  host: orders-db
  subsets:
  - labels:
      name: orders-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 94
        http2MaxRequests: 21
        maxRequestsPerConnection: 8
        maxRetries: 33
      tcp:
        connectTimeout: 84ms
        maxConnections: 73
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payment
  namespace: sock-shop
spec:
  host: payment
  subsets:
  - labels:
      name: payment
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 78
        http2MaxRequests: 25
        maxRequestsPerConnection: 51
        maxRetries: 27
      tcp:
        connectTimeout: 7ms
        maxConnections: 75
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: queue-master
  namespace: sock-shop
spec:
  host: queue-master
  subsets:
  - labels:
      name: queue-master
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 19
        http2MaxRequests: 84
        maxRequestsPerConnection: 79
        maxRetries: 77
      tcp:
        connectTimeout: 17ms
        maxConnections: 41
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rabbitmq
  namespace: sock-shop
spec:
  host: rabbitmq
  subsets:
  - labels:
      name: rabbitmq
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 23
        http2MaxRequests: 63
        maxRequestsPerConnection: 14
        maxRetries: 233
      tcp:
        connectTimeout: 17ms
        maxConnections: 7
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: session-db
  namespace: sock-shop
spec:
  host: session-db
  subsets:
  - labels:
      name: session-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 27
        http2MaxRequests: 13
        maxRequestsPerConnection: 14
        maxRetries: 12
      tcp:
        connectTimeout: 95ms
        maxConnections: 62
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: shipping
  namespace: sock-shop
spec:
  host: shipping
  subsets:
  - labels:
      name: shipping
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 17
        http2MaxRequests: 76
        maxRequestsPerConnection: 66
        maxRetries: 60
      tcp:
        connectTimeout: 38ms
        maxConnections: 19
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user
  namespace: sock-shop
spec:
  host: user
  subsets:
  - labels:
      name: user
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 80
        http2MaxRequests: 33
        maxRequestsPerConnection: 57
        maxRetries: 9
      tcp:
        connectTimeout: 26ms
        maxConnections: 12
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-db
  namespace: sock-shop
spec:
  host: user-db
  subsets:
  - labels:
      name: user-db
      version: v1
    name: v1
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 53
        http2MaxRequests: 63
        maxRequestsPerConnection: 11
        maxRetries: 70
      tcp:
        connectTimeout: 93ms
        maxConnections: 67
